# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finaldialogbox.ui'
#
# Created: Wed Jul 20 16:08:06 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_finalDialog(object):
    def setupUi(self, finalDialog):
        finalDialog.setObjectName("finalDialog")
        finalDialog.resize(545, 202)
        font = QtGui.QFont()
        font.setPointSize(12)
        finalDialog.setFont(font)
        self.gridLayout = QtGui.QGridLayout(finalDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.final_222_batchNo = QtGui.QLabel(finalDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.final_222_batchNo.setFont(font)
        self.final_222_batchNo.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.final_222_batchNo.setObjectName("final_222_batchNo")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.final_222_batchNo)
        self.final_222_batchNo_le = QtGui.QLineEdit(finalDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.final_222_batchNo_le.setFont(font)
        self.final_222_batchNo_le.setObjectName("final_222_batchNo_le")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.final_222_batchNo_le)
        self.final_222_expiry = QtGui.QLabel(finalDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.final_222_expiry.setFont(font)
        self.final_222_expiry.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.final_222_expiry.setObjectName("final_222_expiry")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.final_222_expiry)
        self.final_222_expiry_date = QtGui.QDateEdit(finalDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.final_222_expiry_date.setFont(font)
        self.final_222_expiry_date.setObjectName("final_222_expiry_date")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.final_222_expiry_date)
        self.final_varnish_batchNo = QtGui.QLabel(finalDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.final_varnish_batchNo.setFont(font)
        self.final_varnish_batchNo.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.final_varnish_batchNo.setObjectName("final_varnish_batchNo")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.final_varnish_batchNo)
        self.final_varnish_batchNo_le = QtGui.QLineEdit(finalDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.final_varnish_batchNo_le.setFont(font)
        self.final_varnish_batchNo_le.setObjectName("final_varnish_batchNo_le")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.final_varnish_batchNo_le)
        self.final_varnish_expiry = QtGui.QLabel(finalDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.final_varnish_expiry.setFont(font)
        self.final_varnish_expiry.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.final_varnish_expiry.setObjectName("final_varnish_expiry")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.final_varnish_expiry)
        self.final_varnish_expiry_date = QtGui.QDateEdit(finalDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.final_varnish_expiry_date.setFont(font)
        self.final_varnish_expiry_date.setObjectName("final_varnish_expiry_date")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.final_varnish_expiry_date)
        self.final_tech = QtGui.QLabel(finalDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.final_tech.setFont(font)
        self.final_tech.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.final_tech.setObjectName("final_tech")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.final_tech)
        self.final_tech_cb = QtGui.QComboBox(finalDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.final_tech_cb.setFont(font)
        self.final_tech_cb.setObjectName("final_tech_cb")
        self.final_tech_cb.addItem("")
        self.final_tech_cb.setItemText(0, "")
        self.final_tech_cb.addItem("")
        self.final_tech_cb.addItem("")
        self.final_tech_cb.addItem("")
        self.final_tech_cb.addItem("")
        self.final_tech_cb.addItem("")
        self.final_tech_cb.addItem("")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.final_tech_cb)
        self.pushButton = QtGui.QPushButton(finalDialog)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.pushButton)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)

        self.retranslateUi(finalDialog)
        QtCore.QMetaObject.connectSlotsByName(finalDialog)

    def retranslateUi(self, finalDialog):
        finalDialog.setWindowTitle(QtGui.QApplication.translate("finalDialog", "C for Wire Clamp", None, QtGui.QApplication.UnicodeUTF8))
        self.final_222_batchNo.setText(QtGui.QApplication.translate("finalDialog", "222 Batch No.", None, QtGui.QApplication.UnicodeUTF8))
        self.final_222_batchNo_le.setPlaceholderText(QtGui.QApplication.translate("finalDialog", "Enter 222 Batch No.", None, QtGui.QApplication.UnicodeUTF8))
        self.final_222_expiry.setText(QtGui.QApplication.translate("finalDialog", "222 Expiry Date", None, QtGui.QApplication.UnicodeUTF8))
        self.final_222_expiry_date.setDisplayFormat(QtGui.QApplication.translate("finalDialog", "dd/MMM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.final_varnish_batchNo.setText(QtGui.QApplication.translate("finalDialog", "V Batch No.", None, QtGui.QApplication.UnicodeUTF8))
        self.final_varnish_batchNo_le.setPlaceholderText(QtGui.QApplication.translate("finalDialog", "Enter V Batch No.", None, QtGui.QApplication.UnicodeUTF8))
        self.final_varnish_expiry.setText(QtGui.QApplication.translate("finalDialog", "VExpiry Date", None, QtGui.QApplication.UnicodeUTF8))
        self.final_varnish_expiry_date.setDisplayFormat(QtGui.QApplication.translate("finalDialog", "dd/MMM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.final_tech.setText(QtGui.QApplication.translate("finalDialog", "Technician Name", None, QtGui.QApplication.UnicodeUTF8))
        self.final_tech_cb.setItemText(1, QtGui.QApplication.translate("finalDialog", "Technician A", None, QtGui.QApplication.UnicodeUTF8))
        self.final_tech_cb.setItemText(2, QtGui.QApplication.translate("finalDialog", "Technician B", None, QtGui.QApplication.UnicodeUTF8))
        self.final_tech_cb.setItemText(3, QtGui.QApplication.translate("finalDialog", "Technician C", None, QtGui.QApplication.UnicodeUTF8))
        self.final_tech_cb.setItemText(4, QtGui.QApplication.translate("finalDialog", "Technician D", None, QtGui.QApplication.UnicodeUTF8))
        self.final_tech_cb.setItemText(5, QtGui.QApplication.translate("finalDialog", "Technician E", None, QtGui.QApplication.UnicodeUTF8))
        self.final_tech_cb.setItemText(6, QtGui.QApplication.translate("finalDialog", "Technician F", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("finalDialog", "Done", None, QtGui.QApplication.UnicodeUTF8))

