# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'groupbox.ui'
#
# Created: Mon Jul 25 19:02:45 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(425, 173)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.setFont(font)
        Form.setAutoFillBackground(True)
        self.gridLayout_2 = QtGui.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.cb_gluing = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_gluing.setFont(font)
        self.cb_gluing.setAutoExclusive(True)
        self.cb_gluing.setObjectName("cb_gluing")
        self.gridLayout.addWidget(self.cb_gluing, 2, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.cb_final = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_final.setFont(font)
        self.cb_final.setAutoExclusive(True)
        self.cb_final.setObjectName("cb_final")
        self.gridLayout.addWidget(self.cb_final, 2, 2, 1, 1)
        self.pb = QtGui.QProgressBar(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb.setFont(font)
        self.pb.setProperty("value", 0)
        self.pb.setObjectName("pb")
        self.gridLayout.addWidget(self.pb, 3, 1, 1, 2)
        self.cb_pivot = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_pivot.setFont(font)
        self.cb_pivot.setAutoExclusive(True)
        self.cb_pivot.setObjectName("cb_pivot")
        self.gridLayout.addWidget(self.cb_pivot, 2, 1, 1, 1)
        self.pb_info = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_info.setFont(font)
        self.pb_info.setObjectName("pb_info")
        self.gridLayout.addWidget(self.pb_info, 4, 1, 1, 1)
        self.pb_update = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_update.sizePolicy().hasHeightForWidth())
        self.pb_update.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_update.setFont(font)
        self.pb_update.setObjectName("pb_update")
        self.gridLayout.addWidget(self.pb_update, 4, 2, 1, 1)
        self.lcd = QtGui.QLCDNumber(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.lcd.setFont(font)
        self.lcd.setStyleSheet("QLCDNumber{\n"
"        color : rgb(223, 0, 0);\n"
"        background-color : rgb(225, 225, 225) ;\n"
"        font: 15pt \"MS Shell Dlg 2\";\n"
"}")
        self.lcd.setFrameShape(QtGui.QFrame.Panel)
        self.lcd.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcd.setLineWidth(2)
        self.lcd.setNumDigits(3)
        self.lcd.setDigitCount(3)
        self.lcd.setObjectName("lcd")
        self.gridLayout.addWidget(self.lcd, 4, 0, 1, 1)
        self.label_job = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_job.sizePolicy().hasHeightForWidth())
        self.label_job.setSizePolicy(sizePolicy)
        self.label_job.setAlignment(QtCore.Qt.AlignCenter)
        self.label_job.setObjectName("label_job")
        self.gridLayout.addWidget(self.label_job, 1, 0, 1, 3)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.cb_gluing, self.cb_pivot)
        Form.setTabOrder(self.cb_pivot, self.cb_final)
        Form.setTabOrder(self.cb_final, self.pb_info)
        Form.setTabOrder(self.pb_info, self.pb_update)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Tray ", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_gluing.setText(QtGui.QApplication.translate("Form", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Waiting", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_final.setText(QtGui.QApplication.translate("Form", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_pivot.setText(QtGui.QApplication.translate("Form", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_info.setText(QtGui.QApplication.translate("Form", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_update.setText(QtGui.QApplication.translate("Form", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.label_job.setText(QtGui.QApplication.translate("Form", "Job", None, QtGui.QApplication.UnicodeUTF8))

