# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'infodialogbox.ui'
#
# Created: Thu Jul 21 14:53:22 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_infoDialog(object):
    def setupUi(self, infoDialog):
        infoDialog.setObjectName("infoDialog")
        infoDialog.resize(1182, 646)
        font = QtGui.QFont()
        font.setPointSize(12)
        infoDialog.setFont(font)
        infoDialog.setFocusPolicy(QtCore.Qt.NoFocus)
        self.infoDialog_GL2 = QtGui.QGridLayout(infoDialog)
        self.infoDialog_GL2.setObjectName("infoDialog_GL2")
        self.infoDialog_GL = QtGui.QGridLayout()
        self.infoDialog_GL.setHorizontalSpacing(6)
        self.infoDialog_GL.setObjectName("infoDialog_GL")
        self.info_gluingDatetime_start_datetime = QtGui.QDateTimeEdit(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_gluingDatetime_start_datetime.setFont(font)
        self.info_gluingDatetime_start_datetime.setReadOnly(True)
        self.info_gluingDatetime_start_datetime.setObjectName("info_gluingDatetime_start_datetime")
        self.infoDialog_GL.addWidget(self.info_gluingDatetime_start_datetime, 13, 5, 1, 1)
        self.info_jobNo = QtGui.QLabel(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_jobNo.setFont(font)
        self.info_jobNo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_jobNo.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.info_jobNo.setObjectName("info_jobNo")
        self.infoDialog_GL.addWidget(self.info_jobNo, 1, 0, 1, 1)
        self.info_gluingDatetime_start = QtGui.QLabel(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_gluingDatetime_start.setFont(font)
        self.info_gluingDatetime_start.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_gluingDatetime_start.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.info_gluingDatetime_start.setObjectName("info_gluingDatetime_start")
        self.infoDialog_GL.addWidget(self.info_gluingDatetime_start, 13, 4, 1, 1)
        self.info_pivotDatetime_start = QtGui.QLabel(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_pivotDatetime_start.setFont(font)
        self.info_pivotDatetime_start.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_pivotDatetime_start.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.info_pivotDatetime_start.setObjectName("info_pivotDatetime_start")
        self.infoDialog_GL.addWidget(self.info_pivotDatetime_start, 14, 4, 1, 1)
        self.info_finalDatetime_start = QtGui.QLabel(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_finalDatetime_start.setFont(font)
        self.info_finalDatetime_start.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_finalDatetime_start.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.info_finalDatetime_start.setObjectName("info_finalDatetime_start")
        self.infoDialog_GL.addWidget(self.info_finalDatetime_start, 15, 4, 1, 1)
        self.info_pivotDatetime_start_datetime = QtGui.QDateTimeEdit(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_pivotDatetime_start_datetime.setFont(font)
        self.info_pivotDatetime_start_datetime.setReadOnly(True)
        self.info_pivotDatetime_start_datetime.setObjectName("info_pivotDatetime_start_datetime")
        self.infoDialog_GL.addWidget(self.info_pivotDatetime_start_datetime, 14, 5, 1, 1)
        self.info_gluing = QtGui.QLabel(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_gluing.setFont(font)
        self.info_gluing.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_gluing.setWordWrap(False)
        self.info_gluing.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.info_gluing.setObjectName("info_gluing")
        self.infoDialog_GL.addWidget(self.info_gluing, 13, 0, 1, 1)
        self.info_pivot_le = QtGui.QLineEdit(infoDialog)
        self.info_pivot_le.setReadOnly(True)
        self.info_pivot_le.setObjectName("info_pivot_le")
        self.infoDialog_GL.addWidget(self.info_pivot_le, 14, 1, 1, 3)
        self.info_quantity = QtGui.QLabel(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_quantity.setFont(font)
        self.info_quantity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_quantity.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.info_quantity.setObjectName("info_quantity")
        self.infoDialog_GL.addWidget(self.info_quantity, 3, 0, 1, 1)
        self.info_SE_batchNo = QtGui.QLabel(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_SE_batchNo.setFont(font)
        self.info_SE_batchNo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_SE_batchNo.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.info_SE_batchNo.setObjectName("info_SE_batchNo")
        self.infoDialog_GL.addWidget(self.info_SE_batchNo, 5, 0, 1, 1)
        self.info_hysol_batchNo = QtGui.QLabel(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_hysol_batchNo.setFont(font)
        self.info_hysol_batchNo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_hysol_batchNo.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.info_hysol_batchNo.setObjectName("info_hysol_batchNo")
        self.infoDialog_GL.addWidget(self.info_hysol_batchNo, 6, 0, 1, 1)
        self.info_gluing_le = QtGui.QLineEdit(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_gluing_le.setFont(font)
        self.info_gluing_le.setReadOnly(True)
        self.info_gluing_le.setObjectName("info_gluing_le")
        self.infoDialog_GL.addWidget(self.info_gluing_le, 13, 1, 1, 3)
        self.info_pivot = QtGui.QLabel(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_pivot.setFont(font)
        self.info_pivot.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_pivot.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.info_pivot.setObjectName("info_pivot")
        self.infoDialog_GL.addWidget(self.info_pivot, 14, 0, 1, 1)
        self.info_final = QtGui.QLabel(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_final.setFont(font)
        self.info_final.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_final.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.info_final.setObjectName("info_final")
        self.infoDialog_GL.addWidget(self.info_final, 15, 0, 1, 1)
        self.info_final_le = QtGui.QLineEdit(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_final_le.setFont(font)
        self.info_final_le.setReadOnly(True)
        self.info_final_le.setObjectName("info_final_le")
        self.infoDialog_GL.addWidget(self.info_final_le, 15, 1, 1, 3)
        self.info_finalDatetime_start_datetime = QtGui.QDateTimeEdit(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_finalDatetime_start_datetime.setFont(font)
        self.info_finalDatetime_start_datetime.setReadOnly(True)
        self.info_finalDatetime_start_datetime.setObjectName("info_finalDatetime_start_datetime")
        self.infoDialog_GL.addWidget(self.info_finalDatetime_start_datetime, 15, 5, 1, 1)
        self.info_gluingDatetime_end = QtGui.QLabel(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_gluingDatetime_end.setFont(font)
        self.info_gluingDatetime_end.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_gluingDatetime_end.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.info_gluingDatetime_end.setObjectName("info_gluingDatetime_end")
        self.infoDialog_GL.addWidget(self.info_gluingDatetime_end, 13, 6, 1, 1)
        self.info_gluingDatetime_end_datetime = QtGui.QDateTimeEdit(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_gluingDatetime_end_datetime.setFont(font)
        self.info_gluingDatetime_end_datetime.setReadOnly(True)
        self.info_gluingDatetime_end_datetime.setObjectName("info_gluingDatetime_end_datetime")
        self.infoDialog_GL.addWidget(self.info_gluingDatetime_end_datetime, 13, 7, 1, 1)
        self.info_pivotDatetime_end = QtGui.QLabel(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_pivotDatetime_end.setFont(font)
        self.info_pivotDatetime_end.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_pivotDatetime_end.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.info_pivotDatetime_end.setObjectName("info_pivotDatetime_end")
        self.infoDialog_GL.addWidget(self.info_pivotDatetime_end, 14, 6, 1, 1)
        self.info_finalDatetime_end = QtGui.QLabel(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_finalDatetime_end.setFont(font)
        self.info_finalDatetime_end.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_finalDatetime_end.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.info_finalDatetime_end.setObjectName("info_finalDatetime_end")
        self.infoDialog_GL.addWidget(self.info_finalDatetime_end, 15, 6, 1, 1)
        self.info_pivotDatetime_end_datetime = QtGui.QDateTimeEdit(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_pivotDatetime_end_datetime.setFont(font)
        self.info_pivotDatetime_end_datetime.setReadOnly(True)
        self.info_pivotDatetime_end_datetime.setObjectName("info_pivotDatetime_end_datetime")
        self.infoDialog_GL.addWidget(self.info_pivotDatetime_end_datetime, 14, 7, 1, 1)
        self.info_finalDatetime_end_datetime = QtGui.QDateTimeEdit(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_finalDatetime_end_datetime.setFont(font)
        self.info_finalDatetime_end_datetime.setReadOnly(True)
        self.info_finalDatetime_end_datetime.setObjectName("info_finalDatetime_end_datetime")
        self.infoDialog_GL.addWidget(self.info_finalDatetime_end_datetime, 15, 7, 1, 1)
        self.info_serialNo = QtGui.QTableWidget(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.info_serialNo.setFont(font)
        self.info_serialNo.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.info_serialNo.setAlternatingRowColors(True)
        self.info_serialNo.setCornerButtonEnabled(True)
        self.info_serialNo.setObjectName("info_serialNo")
        self.info_serialNo.setColumnCount(10)
        self.info_serialNo.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.info_serialNo.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.info_serialNo.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.info_serialNo.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.info_serialNo.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.info_serialNo.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.info_serialNo.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.info_serialNo.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.info_serialNo.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.info_serialNo.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.info_serialNo.setHorizontalHeaderItem(9, item)
        self.info_serialNo.horizontalHeader().setDefaultSectionSize(130)
        self.info_serialNo.horizontalHeader().setMinimumSectionSize(100)
        self.infoDialog_GL.addWidget(self.info_serialNo, 10, 0, 1, 8)
        self.info_urgent = QtGui.QLabel(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_urgent.setFont(font)
        self.info_urgent.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_urgent.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.info_urgent.setObjectName("info_urgent")
        self.infoDialog_GL.addWidget(self.info_urgent, 3, 5, 1, 1)
        self.info_SE_expiry = QtGui.QLabel(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_SE_expiry.setFont(font)
        self.info_SE_expiry.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_SE_expiry.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.info_SE_expiry.setObjectName("info_SE_expiry")
        self.infoDialog_GL.addWidget(self.info_SE_expiry, 5, 5, 1, 1)
        self.info_hysol_prod_expiry = QtGui.QLabel(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_hysol_prod_expiry.setFont(font)
        self.info_hysol_prod_expiry.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_hysol_prod_expiry.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.info_hysol_prod_expiry.setObjectName("info_hysol_prod_expiry")
        self.infoDialog_GL.addWidget(self.info_hysol_prod_expiry, 6, 5, 1, 1)
        self.info_jobNo_le = QtGui.QLineEdit(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_jobNo_le.setFont(font)
        self.info_jobNo_le.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.info_jobNo_le.setReadOnly(True)
        self.info_jobNo_le.setObjectName("info_jobNo_le")
        self.infoDialog_GL.addWidget(self.info_jobNo_le, 1, 1, 1, 3)
        self.info_quantity_le = QtGui.QLineEdit(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_quantity_le.setFont(font)
        self.info_quantity_le.setReadOnly(True)
        self.info_quantity_le.setObjectName("info_quantity_le")
        self.infoDialog_GL.addWidget(self.info_quantity_le, 3, 1, 1, 2)
        self.info_SE_batchNo_le = QtGui.QLineEdit(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_SE_batchNo_le.setFont(font)
        self.info_SE_batchNo_le.setReadOnly(True)
        self.info_SE_batchNo_le.setObjectName("info_SE_batchNo_le")
        self.infoDialog_GL.addWidget(self.info_SE_batchNo_le, 5, 1, 1, 2)
        self.info_hysol_batchNo_le = QtGui.QLineEdit(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_hysol_batchNo_le.setFont(font)
        self.info_hysol_batchNo_le.setReadOnly(True)
        self.info_hysol_batchNo_le.setObjectName("info_hysol_batchNo_le")
        self.infoDialog_GL.addWidget(self.info_hysol_batchNo_le, 6, 1, 1, 2)
        self.info_urgent_le = QtGui.QLineEdit(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_urgent_le.setFont(font)
        self.info_urgent_le.setReadOnly(True)
        self.info_urgent_le.setObjectName("info_urgent_le")
        self.infoDialog_GL.addWidget(self.info_urgent_le, 3, 6, 1, 2)
        self.info_SE_expiry_date = QtGui.QDateEdit(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_SE_expiry_date.setFont(font)
        self.info_SE_expiry_date.setReadOnly(True)
        self.info_SE_expiry_date.setObjectName("info_SE_expiry_date")
        self.infoDialog_GL.addWidget(self.info_SE_expiry_date, 5, 6, 1, 2)
        self.info_hysol_prod_expiry_date = QtGui.QDateEdit(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_hysol_prod_expiry_date.setFont(font)
        self.info_hysol_prod_expiry_date.setReadOnly(True)
        self.info_hysol_prod_expiry_date.setObjectName("info_hysol_prod_expiry_date")
        self.infoDialog_GL.addWidget(self.info_hysol_prod_expiry_date, 6, 6, 1, 2)
        self.info_partNo = QtGui.QLabel(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_partNo.setFont(font)
        self.info_partNo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_partNo.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.info_partNo.setObjectName("info_partNo")
        self.infoDialog_GL.addWidget(self.info_partNo, 2, 0, 1, 1)
        self.info_partNo_le = QtGui.QLineEdit(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_partNo_le.setFont(font)
        self.info_partNo_le.setReadOnly(True)
        self.info_partNo_le.setObjectName("info_partNo_le")
        self.infoDialog_GL.addWidget(self.info_partNo_le, 2, 1, 1, 3)
        self.info_type_le = QtGui.QLineEdit(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_type_le.setFont(font)
        self.info_type_le.setReadOnly(True)
        self.info_type_le.setObjectName("info_type_le")
        self.infoDialog_GL.addWidget(self.info_type_le, 2, 5, 1, 3)
        self.info_222_expiry_date = QtGui.QDateEdit(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_222_expiry_date.setFont(font)
        self.info_222_expiry_date.setReadOnly(True)
        self.info_222_expiry_date.setObjectName("info_222_expiry_date")
        self.infoDialog_GL.addWidget(self.info_222_expiry_date, 8, 6, 1, 2)
        self.info_SE_orderNo = QtGui.QLabel(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_SE_orderNo.setFont(font)
        self.info_SE_orderNo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_SE_orderNo.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.info_SE_orderNo.setObjectName("info_SE_orderNo")
        self.infoDialog_GL.addWidget(self.info_SE_orderNo, 5, 3, 1, 1)
        self.info_SE_orderNo_le = QtGui.QLineEdit(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_SE_orderNo_le.setFont(font)
        self.info_SE_orderNo_le.setReadOnly(True)
        self.info_SE_orderNo_le.setObjectName("info_SE_orderNo_le")
        self.infoDialog_GL.addWidget(self.info_SE_orderNo_le, 5, 4, 1, 1)
        self.info_hysol_mfg_expiry = QtGui.QLabel(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_hysol_mfg_expiry.setFont(font)
        self.info_hysol_mfg_expiry.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_hysol_mfg_expiry.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.info_hysol_mfg_expiry.setObjectName("info_hysol_mfg_expiry")
        self.infoDialog_GL.addWidget(self.info_hysol_mfg_expiry, 6, 3, 1, 1)
        self.info_hysol_mfg_expiry_date = QtGui.QDateEdit(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_hysol_mfg_expiry_date.setFont(font)
        self.info_hysol_mfg_expiry_date.setReadOnly(True)
        self.info_hysol_mfg_expiry_date.setObjectName("info_hysol_mfg_expiry_date")
        self.infoDialog_GL.addWidget(self.info_hysol_mfg_expiry_date, 6, 4, 1, 1)
        self.info_7471_batchNo = QtGui.QLabel(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_7471_batchNo.setFont(font)
        self.info_7471_batchNo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_7471_batchNo.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.info_7471_batchNo.setObjectName("info_7471_batchNo")
        self.infoDialog_GL.addWidget(self.info_7471_batchNo, 7, 0, 1, 1)
        self.info_7471_expiry = QtGui.QLabel(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_7471_expiry.setFont(font)
        self.info_7471_expiry.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_7471_expiry.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.info_7471_expiry.setObjectName("info_7471_expiry")
        self.infoDialog_GL.addWidget(self.info_7471_expiry, 7, 5, 1, 1)
        self.info_7471_expiry_date = QtGui.QDateEdit(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_7471_expiry_date.setFont(font)
        self.info_7471_expiry_date.setReadOnly(True)
        self.info_7471_expiry_date.setObjectName("info_7471_expiry_date")
        self.infoDialog_GL.addWidget(self.info_7471_expiry_date, 7, 6, 1, 2)
        self.info_222_batchNo = QtGui.QLabel(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_222_batchNo.setFont(font)
        self.info_222_batchNo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_222_batchNo.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.info_222_batchNo.setObjectName("info_222_batchNo")
        self.infoDialog_GL.addWidget(self.info_222_batchNo, 8, 0, 1, 1)
        self.info_varnish_expiry_date = QtGui.QDateEdit(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_varnish_expiry_date.setFont(font)
        self.info_varnish_expiry_date.setReadOnly(True)
        self.info_varnish_expiry_date.setObjectName("info_varnish_expiry_date")
        self.infoDialog_GL.addWidget(self.info_varnish_expiry_date, 9, 6, 1, 2)
        self.info_varnish_batchNo = QtGui.QLabel(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_varnish_batchNo.setFont(font)
        self.info_varnish_batchNo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_varnish_batchNo.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.info_varnish_batchNo.setObjectName("info_varnish_batchNo")
        self.infoDialog_GL.addWidget(self.info_varnish_batchNo, 9, 0, 1, 1)
        self.info_222_expiry = QtGui.QLabel(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_222_expiry.setFont(font)
        self.info_222_expiry.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_222_expiry.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.info_222_expiry.setObjectName("info_222_expiry")
        self.infoDialog_GL.addWidget(self.info_222_expiry, 8, 5, 1, 1)
        self.info_varnish_expiry = QtGui.QLabel(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_varnish_expiry.setFont(font)
        self.info_varnish_expiry.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_varnish_expiry.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.info_varnish_expiry.setObjectName("info_varnish_expiry")
        self.infoDialog_GL.addWidget(self.info_varnish_expiry, 9, 5, 1, 1)
        self.info_jobDate = QtGui.QLabel(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_jobDate.setFont(font)
        self.info_jobDate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_jobDate.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.info_jobDate.setObjectName("info_jobDate")
        self.infoDialog_GL.addWidget(self.info_jobDate, 1, 4, 1, 1)
        self.info_jobDate_date = QtGui.QDateEdit(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_jobDate_date.setFont(font)
        self.info_jobDate_date.setReadOnly(True)
        self.info_jobDate_date.setObjectName("info_jobDate_date")
        self.infoDialog_GL.addWidget(self.info_jobDate_date, 1, 5, 1, 3)
        self.info_type = QtGui.QLabel(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_type.setFont(font)
        self.info_type.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_type.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.info_type.setObjectName("info_type")
        self.infoDialog_GL.addWidget(self.info_type, 2, 4, 1, 1)
        self.info_line_divider = QtGui.QFrame(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_line_divider.setFont(font)
        self.info_line_divider.setFrameShape(QtGui.QFrame.HLine)
        self.info_line_divider.setFrameShadow(QtGui.QFrame.Sunken)
        self.info_line_divider.setObjectName("info_line_divider")
        self.infoDialog_GL.addWidget(self.info_line_divider, 4, 0, 1, 8)
        self.info_7471_batchNo_le = QtGui.QLineEdit(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_7471_batchNo_le.setFont(font)
        self.info_7471_batchNo_le.setReadOnly(True)
        self.info_7471_batchNo_le.setObjectName("info_7471_batchNo_le")
        self.infoDialog_GL.addWidget(self.info_7471_batchNo_le, 7, 1, 1, 3)
        self.info_222_batchNo_le = QtGui.QLineEdit(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_222_batchNo_le.setFont(font)
        self.info_222_batchNo_le.setReadOnly(True)
        self.info_222_batchNo_le.setObjectName("info_222_batchNo_le")
        self.infoDialog_GL.addWidget(self.info_222_batchNo_le, 8, 1, 1, 3)
        self.info_varnish_batchNo_le = QtGui.QLineEdit(infoDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_varnish_batchNo_le.setFont(font)
        self.info_varnish_batchNo_le.setReadOnly(True)
        self.info_varnish_batchNo_le.setObjectName("info_varnish_batchNo_le")
        self.infoDialog_GL.addWidget(self.info_varnish_batchNo_le, 9, 1, 1, 3)
        self.infoDialog_GL2.addLayout(self.infoDialog_GL, 1, 0, 1, 1)

        self.retranslateUi(infoDialog)
        QtCore.QMetaObject.connectSlotsByName(infoDialog)
        infoDialog.setTabOrder(self.info_jobNo_le, self.info_partNo_le)
        infoDialog.setTabOrder(self.info_partNo_le, self.info_quantity_le)
        infoDialog.setTabOrder(self.info_quantity_le, self.info_jobDate_date)
        infoDialog.setTabOrder(self.info_jobDate_date, self.info_type_le)
        infoDialog.setTabOrder(self.info_type_le, self.info_urgent_le)
        infoDialog.setTabOrder(self.info_urgent_le, self.info_SE_batchNo_le)
        infoDialog.setTabOrder(self.info_SE_batchNo_le, self.info_SE_orderNo_le)
        infoDialog.setTabOrder(self.info_SE_orderNo_le, self.info_SE_expiry_date)
        infoDialog.setTabOrder(self.info_SE_expiry_date, self.info_hysol_batchNo_le)
        infoDialog.setTabOrder(self.info_hysol_batchNo_le, self.info_hysol_mfg_expiry_date)
        infoDialog.setTabOrder(self.info_hysol_mfg_expiry_date, self.info_hysol_prod_expiry_date)
        infoDialog.setTabOrder(self.info_hysol_prod_expiry_date, self.info_7471_batchNo_le)
        infoDialog.setTabOrder(self.info_7471_batchNo_le, self.info_7471_expiry_date)
        infoDialog.setTabOrder(self.info_7471_expiry_date, self.info_222_batchNo_le)
        infoDialog.setTabOrder(self.info_222_batchNo_le, self.info_222_expiry_date)
        infoDialog.setTabOrder(self.info_222_expiry_date, self.info_varnish_batchNo_le)
        infoDialog.setTabOrder(self.info_varnish_batchNo_le, self.info_varnish_expiry_date)
        infoDialog.setTabOrder(self.info_varnish_expiry_date, self.info_serialNo)
        infoDialog.setTabOrder(self.info_serialNo, self.info_gluing_le)
        infoDialog.setTabOrder(self.info_gluing_le, self.info_gluingDatetime_start_datetime)
        infoDialog.setTabOrder(self.info_gluingDatetime_start_datetime, self.info_gluingDatetime_end_datetime)
        infoDialog.setTabOrder(self.info_gluingDatetime_end_datetime, self.info_pivot_le)
        infoDialog.setTabOrder(self.info_pivot_le, self.info_pivotDatetime_start_datetime)
        infoDialog.setTabOrder(self.info_pivotDatetime_start_datetime, self.info_pivotDatetime_end_datetime)
        infoDialog.setTabOrder(self.info_pivotDatetime_end_datetime, self.info_final_le)
        infoDialog.setTabOrder(self.info_final_le, self.info_finalDatetime_start_datetime)
        infoDialog.setTabOrder(self.info_finalDatetime_start_datetime, self.info_finalDatetime_end_datetime)

    def retranslateUi(self, infoDialog):
        infoDialog.setWindowTitle(QtGui.QApplication.translate("infoDialog", "Information", None, QtGui.QApplication.UnicodeUTF8))
        self.info_gluingDatetime_start_datetime.setDisplayFormat(QtGui.QApplication.translate("infoDialog", "dd/MMM/yyyy h:mm:ss AP", None, QtGui.QApplication.UnicodeUTF8))
        self.info_jobNo.setText(QtGui.QApplication.translate("infoDialog", "Job Number", None, QtGui.QApplication.UnicodeUTF8))
        self.info_gluingDatetime_start.setText(QtGui.QApplication.translate("infoDialog", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.info_pivotDatetime_start.setText(QtGui.QApplication.translate("infoDialog", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.info_finalDatetime_start.setText(QtGui.QApplication.translate("infoDialog", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.info_pivotDatetime_start_datetime.setDisplayFormat(QtGui.QApplication.translate("infoDialog", "dd/MMM/yyyy h:mm:ss AP", None, QtGui.QApplication.UnicodeUTF8))
        self.info_gluing.setText(QtGui.QApplication.translate("infoDialog", "Process A Done by", None, QtGui.QApplication.UnicodeUTF8))
        self.info_quantity.setText(QtGui.QApplication.translate("infoDialog", "Quantity", None, QtGui.QApplication.UnicodeUTF8))
        self.info_SE_batchNo.setText(QtGui.QApplication.translate("infoDialog", "SE Batch No.", None, QtGui.QApplication.UnicodeUTF8))
        self.info_hysol_batchNo.setText(QtGui.QApplication.translate("infoDialog", "H Batch No.", None, QtGui.QApplication.UnicodeUTF8))
        self.info_pivot.setText(QtGui.QApplication.translate("infoDialog", "Process B Done by", None, QtGui.QApplication.UnicodeUTF8))
        self.info_final.setText(QtGui.QApplication.translate("infoDialog", "Process C Done by", None, QtGui.QApplication.UnicodeUTF8))
        self.info_finalDatetime_start_datetime.setDisplayFormat(QtGui.QApplication.translate("infoDialog", "dd/MMM/yyyy h:mm:ss AP", None, QtGui.QApplication.UnicodeUTF8))
        self.info_gluingDatetime_end.setText(QtGui.QApplication.translate("infoDialog", "End", None, QtGui.QApplication.UnicodeUTF8))
        self.info_gluingDatetime_end_datetime.setDisplayFormat(QtGui.QApplication.translate("infoDialog", "dd/MMM/yyyy h:mm:ss AP", None, QtGui.QApplication.UnicodeUTF8))
        self.info_pivotDatetime_end.setText(QtGui.QApplication.translate("infoDialog", "End", None, QtGui.QApplication.UnicodeUTF8))
        self.info_finalDatetime_end.setText(QtGui.QApplication.translate("infoDialog", "End", None, QtGui.QApplication.UnicodeUTF8))
        self.info_pivotDatetime_end_datetime.setDisplayFormat(QtGui.QApplication.translate("infoDialog", "dd/MMM/yyyy h:mm:ss AP", None, QtGui.QApplication.UnicodeUTF8))
        self.info_finalDatetime_end_datetime.setDisplayFormat(QtGui.QApplication.translate("infoDialog", "dd/MMM/yyyy h:mm:ss AP", None, QtGui.QApplication.UnicodeUTF8))
        self.info_serialNo.setSortingEnabled(True)
        self.info_serialNo.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("infoDialog", "Serial Number", None, QtGui.QApplication.UnicodeUTF8))
        self.info_serialNo.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("infoDialog", "Torque Value", None, QtGui.QApplication.UnicodeUTF8))
        self.info_serialNo.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("infoDialog", "Clamp Force", None, QtGui.QApplication.UnicodeUTF8))
        self.info_serialNo.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("infoDialog", "Remarks", None, QtGui.QApplication.UnicodeUTF8))
        self.info_serialNo.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("infoDialog", "Rework", None, QtGui.QApplication.UnicodeUTF8))
        self.info_serialNo.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("infoDialog", "Rework Type", None, QtGui.QApplication.UnicodeUTF8))
        self.info_serialNo.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("infoDialog", "Submitted by", None, QtGui.QApplication.UnicodeUTF8))
        self.info_serialNo.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("infoDialog", "Time, Date Submitted", None, QtGui.QApplication.UnicodeUTF8))
        self.info_serialNo.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("infoDialog", "Attempted by", None, QtGui.QApplication.UnicodeUTF8))
        self.info_serialNo.horizontalHeaderItem(9).setText(QtGui.QApplication.translate("infoDialog", "Time, Date Attempted", None, QtGui.QApplication.UnicodeUTF8))
        self.info_urgent.setText(QtGui.QApplication.translate("infoDialog", "Urgent", None, QtGui.QApplication.UnicodeUTF8))
        self.info_SE_expiry.setText(QtGui.QApplication.translate("infoDialog", "Expiry Date", None, QtGui.QApplication.UnicodeUTF8))
        self.info_hysol_prod_expiry.setText(QtGui.QApplication.translate("infoDialog", "Production Expiry Date", None, QtGui.QApplication.UnicodeUTF8))
        self.info_SE_expiry_date.setDisplayFormat(QtGui.QApplication.translate("infoDialog", "dd/MMM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.info_hysol_prod_expiry_date.setDisplayFormat(QtGui.QApplication.translate("infoDialog", "dd/MMM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.info_partNo.setText(QtGui.QApplication.translate("infoDialog", "Part Number", None, QtGui.QApplication.UnicodeUTF8))
        self.info_222_expiry_date.setDisplayFormat(QtGui.QApplication.translate("infoDialog", "dd/MMM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.info_SE_orderNo.setText(QtGui.QApplication.translate("infoDialog", "SE Order No.", None, QtGui.QApplication.UnicodeUTF8))
        self.info_hysol_mfg_expiry.setText(QtGui.QApplication.translate("infoDialog", "MFG. Expiry Date", None, QtGui.QApplication.UnicodeUTF8))
        self.info_hysol_mfg_expiry_date.setDisplayFormat(QtGui.QApplication.translate("infoDialog", "dd/MMM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.info_7471_batchNo.setText(QtGui.QApplication.translate("infoDialog", "7471 Batch No.", None, QtGui.QApplication.UnicodeUTF8))
        self.info_7471_expiry.setText(QtGui.QApplication.translate("infoDialog", "Expiry Date", None, QtGui.QApplication.UnicodeUTF8))
        self.info_7471_expiry_date.setDisplayFormat(QtGui.QApplication.translate("infoDialog", "dd/MMM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.info_222_batchNo.setText(QtGui.QApplication.translate("infoDialog", "222 Batch No.", None, QtGui.QApplication.UnicodeUTF8))
        self.info_varnish_expiry_date.setDisplayFormat(QtGui.QApplication.translate("infoDialog", "dd/MMM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.info_varnish_batchNo.setText(QtGui.QApplication.translate("infoDialog", "V Batch No.", None, QtGui.QApplication.UnicodeUTF8))
        self.info_222_expiry.setText(QtGui.QApplication.translate("infoDialog", "Expiry Date", None, QtGui.QApplication.UnicodeUTF8))
        self.info_varnish_expiry.setText(QtGui.QApplication.translate("infoDialog", "Expiry Date", None, QtGui.QApplication.UnicodeUTF8))
        self.info_jobDate.setText(QtGui.QApplication.translate("infoDialog", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.info_jobDate_date.setDisplayFormat(QtGui.QApplication.translate("infoDialog", "dd/MMM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.info_type.setText(QtGui.QApplication.translate("infoDialog", "Type", None, QtGui.QApplication.UnicodeUTF8))

