# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pivotdialogbox.ui'
#
# Created: Wed Jul 20 16:07:01 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_pivotDialog(object):
    def setupUi(self, pivotDialog):
        pivotDialog.setObjectName("pivotDialog")
        pivotDialog.resize(597, 244)
        font = QtGui.QFont()
        font.setPointSize(12)
        pivotDialog.setFont(font)
        self.gridLayout = QtGui.QGridLayout(pivotDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.pivot_hysol_batchNo = QtGui.QLabel(pivotDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pivot_hysol_batchNo.setFont(font)
        self.pivot_hysol_batchNo.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.pivot_hysol_batchNo.setObjectName("pivot_hysol_batchNo")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.pivot_hysol_batchNo)
        self.pivot_hysol_batchNo_le = QtGui.QLineEdit(pivotDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pivot_hysol_batchNo_le.setFont(font)
        self.pivot_hysol_batchNo_le.setObjectName("pivot_hysol_batchNo_le")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.pivot_hysol_batchNo_le)
        self.pivot_hysol_mfgexpiry = QtGui.QLabel(pivotDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pivot_hysol_mfgexpiry.setFont(font)
        self.pivot_hysol_mfgexpiry.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.pivot_hysol_mfgexpiry.setObjectName("pivot_hysol_mfgexpiry")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.pivot_hysol_mfgexpiry)
        self.pivot_hysol_mfgexpiry_date = QtGui.QDateEdit(pivotDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pivot_hysol_mfgexpiry_date.setFont(font)
        self.pivot_hysol_mfgexpiry_date.setObjectName("pivot_hysol_mfgexpiry_date")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.pivot_hysol_mfgexpiry_date)
        self.pivot_hysol_prodexpiry = QtGui.QLabel(pivotDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pivot_hysol_prodexpiry.setFont(font)
        self.pivot_hysol_prodexpiry.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.pivot_hysol_prodexpiry.setObjectName("pivot_hysol_prodexpiry")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.pivot_hysol_prodexpiry)
        self.pivot_hysol_prodexpiry_date = QtGui.QDateEdit(pivotDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pivot_hysol_prodexpiry_date.setFont(font)
        self.pivot_hysol_prodexpiry_date.setCurrentSection(QtGui.QDateTimeEdit.DaySection)
        self.pivot_hysol_prodexpiry_date.setObjectName("pivot_hysol_prodexpiry_date")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.pivot_hysol_prodexpiry_date)
        self.pivot_7471_batchNo = QtGui.QLabel(pivotDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pivot_7471_batchNo.setFont(font)
        self.pivot_7471_batchNo.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.pivot_7471_batchNo.setObjectName("pivot_7471_batchNo")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.pivot_7471_batchNo)
        self.pivot_7471_batchNo_le = QtGui.QLineEdit(pivotDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pivot_7471_batchNo_le.setFont(font)
        self.pivot_7471_batchNo_le.setObjectName("pivot_7471_batchNo_le")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.pivot_7471_batchNo_le)
        self.pivot_7471_expiry = QtGui.QLabel(pivotDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pivot_7471_expiry.setFont(font)
        self.pivot_7471_expiry.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.pivot_7471_expiry.setObjectName("pivot_7471_expiry")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.pivot_7471_expiry)
        self.pivot_7471_expiry_date = QtGui.QDateEdit(pivotDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pivot_7471_expiry_date.setFont(font)
        self.pivot_7471_expiry_date.setObjectName("pivot_7471_expiry_date")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.pivot_7471_expiry_date)
        self.pivot_tech = QtGui.QLabel(pivotDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pivot_tech.setFont(font)
        self.pivot_tech.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.pivot_tech.setObjectName("pivot_tech")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.pivot_tech)
        self.pivot_tech_cb = QtGui.QComboBox(pivotDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pivot_tech_cb.setFont(font)
        self.pivot_tech_cb.setObjectName("pivot_tech_cb")
        self.pivot_tech_cb.addItem("")
        self.pivot_tech_cb.setItemText(0, "")
        self.pivot_tech_cb.addItem("")
        self.pivot_tech_cb.addItem("")
        self.pivot_tech_cb.addItem("")
        self.pivot_tech_cb.addItem("")
        self.pivot_tech_cb.addItem("")
        self.pivot_tech_cb.addItem("")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.pivot_tech_cb)
        self.pushButton = QtGui.QPushButton(pivotDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.pushButton)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)

        self.retranslateUi(pivotDialog)
        QtCore.QMetaObject.connectSlotsByName(pivotDialog)

    def retranslateUi(self, pivotDialog):
        pivotDialog.setWindowTitle(QtGui.QApplication.translate("pivotDialog", "Process B for Wire Clamp", None, QtGui.QApplication.UnicodeUTF8))
        self.pivot_hysol_batchNo.setText(QtGui.QApplication.translate("pivotDialog", "Batch No.", None, QtGui.QApplication.UnicodeUTF8))
        self.pivot_hysol_batchNo_le.setPlaceholderText(QtGui.QApplication.translate("pivotDialog", "Enter the Batch No.", None, QtGui.QApplication.UnicodeUTF8))
        self.pivot_hysol_mfgexpiry.setText(QtGui.QApplication.translate("pivotDialog", "Manufacturing Expiry Date", None, QtGui.QApplication.UnicodeUTF8))
        self.pivot_hysol_mfgexpiry_date.setDisplayFormat(QtGui.QApplication.translate("pivotDialog", "dd/MMM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.pivot_hysol_prodexpiry.setText(QtGui.QApplication.translate("pivotDialog", "Production Expiry Date", None, QtGui.QApplication.UnicodeUTF8))
        self.pivot_hysol_prodexpiry_date.setDisplayFormat(QtGui.QApplication.translate("pivotDialog", "dd/MMM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.pivot_7471_batchNo.setText(QtGui.QApplication.translate("pivotDialog", "Batch No.2", None, QtGui.QApplication.UnicodeUTF8))
        self.pivot_7471_batchNo_le.setPlaceholderText(QtGui.QApplication.translate("pivotDialog", "Enter Batch No.2", None, QtGui.QApplication.UnicodeUTF8))
        self.pivot_7471_expiry.setText(QtGui.QApplication.translate("pivotDialog", "Expiry Date", None, QtGui.QApplication.UnicodeUTF8))
        self.pivot_7471_expiry_date.setDisplayFormat(QtGui.QApplication.translate("pivotDialog", "dd/MMM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.pivot_tech.setText(QtGui.QApplication.translate("pivotDialog", "Technician Name", None, QtGui.QApplication.UnicodeUTF8))
        self.pivot_tech_cb.setItemText(1, QtGui.QApplication.translate("pivotDialog", "Technician A", None, QtGui.QApplication.UnicodeUTF8))
        self.pivot_tech_cb.setItemText(2, QtGui.QApplication.translate("pivotDialog", "Technician B", None, QtGui.QApplication.UnicodeUTF8))
        self.pivot_tech_cb.setItemText(3, QtGui.QApplication.translate("pivotDialog", "Technician C", None, QtGui.QApplication.UnicodeUTF8))
        self.pivot_tech_cb.setItemText(4, QtGui.QApplication.translate("pivotDialog", "Technician D", None, QtGui.QApplication.UnicodeUTF8))
        self.pivot_tech_cb.setItemText(5, QtGui.QApplication.translate("pivotDialog", "Technician E", None, QtGui.QApplication.UnicodeUTF8))
        self.pivot_tech_cb.setItemText(6, QtGui.QApplication.translate("pivotDialog", "Technician F", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("pivotDialog", "Done", None, QtGui.QApplication.UnicodeUTF8))

