# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'production manager v2.ui'
#
# Created: Mon Jul 25 15:58:02 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1910, 943)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.componentTab = QtGui.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.componentTab.setFont(font)
        self.componentTab.setTabShape(QtGui.QTabWidget.Triangular)
        self.componentTab.setMovable(True)
        self.componentTab.setObjectName("componentTab")
        self.wc = QtGui.QWidget()
        self.wc.setObjectName("wc")
        self.gridLayout_3 = QtGui.QGridLayout(self.wc)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.wcprocessTab = QtGui.QTabWidget(self.wc)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.wcprocessTab.setFont(font)
        self.wcprocessTab.setObjectName("wcprocessTab")
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName("tab1")
        self.gridLayout_51 = QtGui.QGridLayout(self.tab1)
        self.gridLayout_51.setObjectName("gridLayout_51")
        self.GL_orders = QtGui.QGridLayout()
        self.GL_orders.setObjectName("GL_orders")
        self.gridLayout_51.addLayout(self.GL_orders, 0, 0, 1, 1)
        self.wcprocessTab.addTab(self.tab1, "")
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName("tab2")
        self.gridLayout_52 = QtGui.QGridLayout(self.tab2)
        self.gridLayout_52.setObjectName("gridLayout_52")
        self.GL_gluing = QtGui.QGridLayout()
        self.GL_gluing.setObjectName("GL_gluing")
        self.gridLayout_52.addLayout(self.GL_gluing, 0, 0, 1, 1)
        self.wcprocessTab.addTab(self.tab2, "")
        self.tab3 = QtGui.QWidget()
        self.tab3.setObjectName("tab3")
        self.gridLayout_53 = QtGui.QGridLayout(self.tab3)
        self.gridLayout_53.setObjectName("gridLayout_53")
        self.GL_pivot = QtGui.QGridLayout()
        self.GL_pivot.setObjectName("GL_pivot")
        self.gridLayout_53.addLayout(self.GL_pivot, 0, 0, 1, 1)
        self.wcprocessTab.addTab(self.tab3, "")
        self.tab4 = QtGui.QWidget()
        self.tab4.setObjectName("tab4")
        self.gridLayout_6 = QtGui.QGridLayout(self.tab4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.GL_final = QtGui.QGridLayout()
        self.GL_final.setObjectName("GL_final")
        self.gridLayout_6.addLayout(self.GL_final, 0, 0, 1, 1)
        self.wcprocessTab.addTab(self.tab4, "")
        self.tab5 = QtGui.QWidget()
        self.tab5.setObjectName("tab5")
        self.gridLayout_4 = QtGui.QGridLayout(self.tab5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.GL_feedtube = QtGui.QGridLayout()
        self.GL_feedtube.setObjectName("GL_feedtube")
        self.gridLayout_4.addLayout(self.GL_feedtube, 0, 0, 1, 1)
        self.wcprocessTab.addTab(self.tab5, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtGui.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.GL_completed = QtGui.QGridLayout()
        self.GL_completed.setObjectName("GL_completed")
        self.gridLayout_5.addLayout(self.GL_completed, 0, 0, 1, 1)
        self.wcprocessTab.addTab(self.tab, "")
        self.gridLayout_3.addWidget(self.wcprocessTab, 0, 0, 1, 1)
        self.componentTab.addTab(self.wc, "")
        self.transducer = QtGui.QWidget()
        self.transducer.setObjectName("Transducer")
        self.componentTab.addTab(self.transducer, "")
        self.bh = QtGui.QWidget()
        self.bh.setObjectName("bh")
        self.componentTab.addTab(self.bh, "")
        self.gridLayout_2.addWidget(self.componentTab, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1910, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuExport = QtGui.QMenu(self.menuFile)
        self.menuExport.setObjectName("menuExport")
        self.menuOracle_ERP = QtGui.QMenu(self.menuExport)
        self.menuOracle_ERP.setObjectName("menuOracle_ERP")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionText = QtGui.QAction(MainWindow)
        self.actionText.setObjectName("actionText")
        self.actionCSV = QtGui.QAction(MainWindow)
        self.actionCSV.setObjectName("actionCSV")
        self.actionAdd = QtGui.QAction(MainWindow)
        self.actionAdd.setCheckable(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionAdd.setFont(font)
        self.actionAdd.setObjectName("actionAdd")
        self.actionBasic = QtGui.QAction(MainWindow)
        self.actionBasic.setObjectName("actionBasic")
        self.actionDetailed = QtGui.QAction(MainWindow)
        self.actionDetailed.setObjectName("actionDetailed")
        self.menuOracle_ERP.addAction(self.actionBasic)
        self.menuOracle_ERP.addAction(self.actionDetailed)
        self.menuExport.addAction(self.actionCSV)
        self.menuExport.addAction(self.menuOracle_ERP.menuAction())
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionAdd)

        self.retranslateUi(MainWindow)
        self.componentTab.setCurrentIndex(0)
        self.wcprocessTab.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.componentTab, self.wcprocessTab)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Production Manager V2.0", None, QtGui.QApplication.UnicodeUTF8))
        self.wcprocessTab.setTabText(self.wcprocessTab.indexOf(self.tab1), QtGui.QApplication.translate("MainWindow", "Orders", None, QtGui.QApplication.UnicodeUTF8))
        self.wcprocessTab.setTabText(self.wcprocessTab.indexOf(self.tab2), QtGui.QApplication.translate("MainWindow", "Process A", None, QtGui.QApplication.UnicodeUTF8))
        self.wcprocessTab.setTabText(self.wcprocessTab.indexOf(self.tab3), QtGui.QApplication.translate("MainWindow", "Process B", None, QtGui.QApplication.UnicodeUTF8))
        self.wcprocessTab.setTabText(self.wcprocessTab.indexOf(self.tab4), QtGui.QApplication.translate("MainWindow", "Process C", None, QtGui.QApplication.UnicodeUTF8))
        self.wcprocessTab.setTabText(self.wcprocessTab.indexOf(self.tab5), QtGui.QApplication.translate("MainWindow", "Item FT", None, QtGui.QApplication.UnicodeUTF8))
        self.wcprocessTab.setTabText(self.wcprocessTab.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Completed", None, QtGui.QApplication.UnicodeUTF8))
        self.componentTab.setTabText(self.componentTab.indexOf(self.wc), QtGui.QApplication.translate("MainWindow", "Item A", None, QtGui.QApplication.UnicodeUTF8))
        self.componentTab.setTabText(self.componentTab.indexOf(self.transducer), QtGui.QApplication.translate("MainWindow", "Item B", None, QtGui.QApplication.UnicodeUTF8))
        self.componentTab.setTabText(self.componentTab.indexOf(self.bh), QtGui.QApplication.translate("MainWindow", "Item C", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuExport.setTitle(QtGui.QApplication.translate("MainWindow", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOracle_ERP.setTitle(QtGui.QApplication.translate("MainWindow", "Oracle CSV", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionText.setText(QtGui.QApplication.translate("MainWindow", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCSV.setText(QtGui.QApplication.translate("MainWindow", "FULL CSV", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd.setText(QtGui.QApplication.translate("MainWindow", "Add New Job", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBasic.setText(QtGui.QApplication.translate("MainWindow", "Basic", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDetailed.setText(QtGui.QApplication.translate("MainWindow", "Detailed", None, QtGui.QApplication.UnicodeUTF8))

