# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updatedialogbox.ui'
#
# Created: Mon Jul 25 17:08:29 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1294, 639)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtGui.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.update_pb_gluing = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.update_pb_gluing.setFont(font)
        self.update_pb_gluing.setObjectName("update_pb_gluing")
        self.horizontalLayout.addWidget(self.update_pb_gluing)
        self.update_pb_pivot = QtGui.QPushButton(self.groupBox)
        self.update_pb_pivot.setObjectName("update_pb_pivot")
        self.horizontalLayout.addWidget(self.update_pb_pivot)
        self.update_pb_final = QtGui.QPushButton(self.groupBox)
        self.update_pb_final.setObjectName("update_pb_final")
        self.horizontalLayout.addWidget(self.update_pb_final)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtGui.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.update_serialno_attempt_cb = QtGui.QComboBox(self.groupBox_4)
        self.update_serialno_attempt_cb.setObjectName("update_serialno_attempt_cb")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.update_serialno_attempt_cb)
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.update_doneby_attempt_cb = QtGui.QComboBox(self.groupBox_4)
        self.update_doneby_attempt_cb.setObjectName("update_doneby_attempt_cb")
        self.update_doneby_attempt_cb.addItem("")
        self.update_doneby_attempt_cb.setItemText(0, "")
        self.update_doneby_attempt_cb.addItem("")
        self.update_doneby_attempt_cb.addItem("")
        self.update_doneby_attempt_cb.addItem("")
        self.update_doneby_attempt_cb.addItem("")
        self.update_doneby_attempt_cb.addItem("")
        self.update_doneby_attempt_cb.addItem("")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.update_doneby_attempt_cb)
        self.update_pb_attempt_rework = QtGui.QPushButton(self.groupBox_4)
        self.update_pb_attempt_rework.setObjectName("update_pb_attempt_rework")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.SpanningRole, self.update_pb_attempt_rework)
        self.gridLayout_8.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 3, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.update_tray_tw = QtGui.QTableWidget(self.groupBox_2)
        self.update_tray_tw.setObjectName("update_tray_tw")
        self.update_tray_tw.setColumnCount(10)
        self.update_tray_tw.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.update_tray_tw.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.update_tray_tw.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.update_tray_tw.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.update_tray_tw.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.update_tray_tw.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.update_tray_tw.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.update_tray_tw.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.update_tray_tw.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.update_tray_tw.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.update_tray_tw.setHorizontalHeaderItem(9, item)
        self.update_tray_tw.horizontalHeader().setDefaultSectionSize(130)
        self.update_tray_tw.horizontalHeader().setMinimumSectionSize(100)
        self.gridLayout_3.addWidget(self.update_tray_tw, 0, 0, 1, 1)
        self.update_tray_pb = QtGui.QPushButton(self.groupBox_2)
        self.update_tray_pb.setObjectName("update_tray_pb")
        self.gridLayout_3.addWidget(self.update_tray_pb, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.update_serialno_declare_cb = QtGui.QComboBox(self.groupBox_3)
        self.update_serialno_declare_cb.setObjectName("update_serialno_declare_cb")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.update_serialno_declare_cb)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.update_type_cb = QtGui.QComboBox(self.groupBox_3)
        self.update_type_cb.setObjectName("update_type_cb")
        self.update_type_cb.addItem("")
        self.update_type_cb.setItemText(0, "")
        self.update_type_cb.addItem("")
        self.update_type_cb.addItem("")
        self.update_type_cb.addItem("")
        self.update_type_cb.addItem("")
        self.update_type_cb.addItem("")
        self.update_type_cb.addItem("")
        self.update_type_cb.addItem("")
        self.update_type_cb.addItem("")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.update_type_cb)
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.update_doneby_declare_cb = QtGui.QComboBox(self.groupBox_3)
        self.update_doneby_declare_cb.setObjectName("update_doneby_declare_cb")
        self.update_doneby_declare_cb.addItem("")
        self.update_doneby_declare_cb.setItemText(0, "")
        self.update_doneby_declare_cb.addItem("")
        self.update_doneby_declare_cb.addItem("")
        self.update_doneby_declare_cb.addItem("")
        self.update_doneby_declare_cb.addItem("")
        self.update_doneby_declare_cb.addItem("")
        self.update_doneby_declare_cb.addItem("")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.update_doneby_declare_cb)
        self.update_pb_declare_rework = QtGui.QPushButton(self.groupBox_3)
        self.update_pb_declare_rework.setObjectName("update_pb_declare_rework")
        self.formLayout.setWidget(3, QtGui.QFormLayout.SpanningRole, self.update_pb_declare_rework)
        self.gridLayout_7.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.update_pb_gluing, self.update_pb_pivot)
        Dialog.setTabOrder(self.update_pb_pivot, self.update_pb_final)
        Dialog.setTabOrder(self.update_pb_final, self.update_tray_tw)
        Dialog.setTabOrder(self.update_tray_tw, self.update_tray_pb)
        Dialog.setTabOrder(self.update_tray_pb, self.update_serialno_declare_cb)
        Dialog.setTabOrder(self.update_serialno_declare_cb, self.update_type_cb)
        Dialog.setTabOrder(self.update_type_cb, self.update_doneby_declare_cb)
        Dialog.setTabOrder(self.update_doneby_declare_cb, self.update_pb_declare_rework)
        Dialog.setTabOrder(self.update_pb_declare_rework, self.update_serialno_attempt_cb)
        Dialog.setTabOrder(self.update_serialno_attempt_cb, self.update_doneby_attempt_cb)
        Dialog.setTabOrder(self.update_doneby_attempt_cb, self.update_pb_attempt_rework)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Update Tray", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Completed", None, QtGui.QApplication.UnicodeUTF8))
        self.update_pb_gluing.setText(QtGui.QApplication.translate("Dialog", "Gluing", None, QtGui.QApplication.UnicodeUTF8))
        self.update_pb_pivot.setText(QtGui.QApplication.translate("Dialog", "Pivot", None, QtGui.QApplication.UnicodeUTF8))
        self.update_pb_final.setText(QtGui.QApplication.translate("Dialog", "Final", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Dialog", "Rework Attempt Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Serial Number", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Done By", None, QtGui.QApplication.UnicodeUTF8))
        self.update_doneby_attempt_cb.setItemText(1, QtGui.QApplication.translate("Dialog", "60008229", None, QtGui.QApplication.UnicodeUTF8))
        self.update_doneby_attempt_cb.setItemText(2, QtGui.QApplication.translate("Dialog", "H0023", None, QtGui.QApplication.UnicodeUTF8))
        self.update_doneby_attempt_cb.setItemText(3, QtGui.QApplication.translate("Dialog", "60013479", None, QtGui.QApplication.UnicodeUTF8))
        self.update_doneby_attempt_cb.setItemText(4, QtGui.QApplication.translate("Dialog", "T9942", None, QtGui.QApplication.UnicodeUTF8))
        self.update_doneby_attempt_cb.setItemText(5, QtGui.QApplication.translate("Dialog", "60014194", None, QtGui.QApplication.UnicodeUTF8))
        self.update_doneby_attempt_cb.setItemText(6, QtGui.QApplication.translate("Dialog", "H0017", None, QtGui.QApplication.UnicodeUTF8))
        self.update_pb_attempt_rework.setText(QtGui.QApplication.translate("Dialog", "Submit Rework Attempt Application", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Update Tray Information - Torque Value, Clamp Force, Remarks", None, QtGui.QApplication.UnicodeUTF8))
        self.update_tray_tw.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Serial Number", None, QtGui.QApplication.UnicodeUTF8))
        self.update_tray_tw.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "Torque Value", None, QtGui.QApplication.UnicodeUTF8))
        self.update_tray_tw.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog", "Clamp Force", None, QtGui.QApplication.UnicodeUTF8))
        self.update_tray_tw.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Dialog", "Remarks", None, QtGui.QApplication.UnicodeUTF8))
        self.update_tray_tw.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Dialog", "Rework", None, QtGui.QApplication.UnicodeUTF8))
        self.update_tray_tw.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Dialog", "Rework Type", None, QtGui.QApplication.UnicodeUTF8))
        self.update_tray_tw.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("Dialog", "Submitted by", None, QtGui.QApplication.UnicodeUTF8))
        self.update_tray_tw.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("Dialog", "Time, Date Submitted", None, QtGui.QApplication.UnicodeUTF8))
        self.update_tray_tw.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("Dialog", "Attempted by", None, QtGui.QApplication.UnicodeUTF8))
        self.update_tray_tw.horizontalHeaderItem(9).setText(QtGui.QApplication.translate("Dialog", "Time, Date Attempted", None, QtGui.QApplication.UnicodeUTF8))
        self.update_tray_pb.setText(QtGui.QApplication.translate("Dialog", "Submit, Save and update Database", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Rework Declaration Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Serial Number", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Rework Type", None, QtGui.QApplication.UnicodeUTF8))
        self.update_type_cb.setItemText(1, QtGui.QApplication.translate("Dialog", "Jewel Stained", None, QtGui.QApplication.UnicodeUTF8))
        self.update_type_cb.setItemText(2, QtGui.QApplication.translate("Dialog", "Jewel Dropped", None, QtGui.QApplication.UnicodeUTF8))
        self.update_type_cb.setItemText(3, QtGui.QApplication.translate("Dialog", "Soft Glue", None, QtGui.QApplication.UnicodeUTF8))
        self.update_type_cb.setItemText(4, QtGui.QApplication.translate("Dialog", "Clamp Force", None, QtGui.QApplication.UnicodeUTF8))
        self.update_type_cb.setItemText(5, QtGui.QApplication.translate("Dialog", "Torque Value", None, QtGui.QApplication.UnicodeUTF8))
        self.update_type_cb.setItemText(6, QtGui.QApplication.translate("Dialog", "Parallelism Off", None, QtGui.QApplication.UnicodeUTF8))
        self.update_type_cb.setItemText(7, QtGui.QApplication.translate("Dialog", "Wireclamp Offset", None, QtGui.QApplication.UnicodeUTF8))
        self.update_type_cb.setItemText(8, QtGui.QApplication.translate("Dialog", "Scrap", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Done by", None, QtGui.QApplication.UnicodeUTF8))
        self.update_doneby_declare_cb.setItemText(1, QtGui.QApplication.translate("Dialog", "60008229", None, QtGui.QApplication.UnicodeUTF8))
        self.update_doneby_declare_cb.setItemText(2, QtGui.QApplication.translate("Dialog", "H0023", None, QtGui.QApplication.UnicodeUTF8))
        self.update_doneby_declare_cb.setItemText(3, QtGui.QApplication.translate("Dialog", "60013479", None, QtGui.QApplication.UnicodeUTF8))
        self.update_doneby_declare_cb.setItemText(4, QtGui.QApplication.translate("Dialog", "T9942", None, QtGui.QApplication.UnicodeUTF8))
        self.update_doneby_declare_cb.setItemText(5, QtGui.QApplication.translate("Dialog", "60014194", None, QtGui.QApplication.UnicodeUTF8))
        self.update_doneby_declare_cb.setItemText(6, QtGui.QApplication.translate("Dialog", "H0017", None, QtGui.QApplication.UnicodeUTF8))
        self.update_pb_declare_rework.setText(QtGui.QApplication.translate("Dialog", "Submit Rework Application", None, QtGui.QApplication.UnicodeUTF8))

